version: 2

updates:

  # Backend Maven
  - package-ecosystem: "maven"
    directory: "/backend/pipes-bakery-backend"
    schedule:
      interval: "weekly"

  # Frontend npm
  - package-ecosystem: "npm"
    directory: "/frontend/pipes-bakery-frontend"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"