services:
  mysql:
    image: mysql:8
    container_name: bakery-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pipes_bakery
      MYSQL_USER: pipes_user
      MYSQL_PASSWORD: pipes_password
    ports:
      - "3306:3306"
    volumes:
      - pipes-bakery-backend_mysql-data:/var/lib/mysql
    networks:
      - bakery-network

  redis:
    image: redis:7
    container_name: bakery-redis
    ports:
      - "6379:6379"
    networks:
      - bakery-network

networks:
  bakery-network:

volumes:
  pipes-bakery-backend_mysql-data:
    external: true