spring.application.name=pipes-bakery-backend

spring.datasource.url=jdbc:mysql://localhost:3306/pipes_bakery
spring.datasource.username=pipes_user
spring.datasource.password=pipes_password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Solo para desarrollo, en producción se debe usar "validate" o "none"
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.web.resources.add-mappings=false

